-- Script consolidado para la creación de todas las tablas

-- Crear la tabla AlpesCab
CREATE TABLE AlpesCab (
    idSistema NUMBER PRIMARY KEY,
    nombre VARCHAR2(100)
);

-- Crear la tabla Ciudad
CREATE TABLE Ciudad (
    idCiudad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) UNIQUE NOT NULL
);

-- Crear la tabla PuntoGeografico
CREATE TABLE PuntoGeografico (
    idPunto NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(200) UNIQUE NOT NULL,
    latitud NUMBER(10,7) NOT NULL,
    longitud NUMBER(10,7) NOT NULL,
    ciudad NUMBER NOT NULL,
    CONSTRAINT fk_ciudad FOREIGN KEY (Ciudad) REFERENCES Ciudad(idCiudad)
);

-- Crear la tabla Usuario
CREATE TABLE Usuario (
    cedula        VARCHAR2(20) PRIMARY KEY,
    nombre        VARCHAR2(150) NOT NULL,
    correo        VARCHAR2(150) NOT NULL UNIQUE,
    celular       VARCHAR2(30) NOT NULL,
    tipo          VARCHAR2(20) NOT NULL,
    calificacion  NUMBER(3,2),
    comentario    VARCHAR2(4000)
);

-- Crear la tabla UsuarioCliente
CREATE TABLE UsuarioCliente (
    cedulaCliente VARCHAR2(20) PRIMARY KEY NOT NULL REFERENCES Usuario(cedula)
);

-- Crear la tabla UsuarioCoductor
CREATE TABLE UsuarioCoductor (
    cedulaConductor VARCHAR2(20) PRIMARY KEY NOT NULL REFERENCES Usuario(cedula)
);

-- Crear la tabla Vehiculo
CREATE TABLE Vehiculo (
    placa VARCHAR2(20) PRIMARY KEY,
    cedula VARCHAR2(20),
    tipo VARCHAR2(50),
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    color VARCHAR2(30),
    capacidadPasajeros NUMBER,
    ciudadExpedicion NUMBER,
    registrado NUMBER(1),
    CONSTRAINT fk_vehiculo_usuario FOREIGN KEY (cedula) REFERENCES Usuario(cedula),
    CONSTRAINT fk_vehiculo_ciudad FOREIGN KEY (ciudadExpedicion) REFERENCES Ciudad(idCiudad)
);

-- Crear la tabla Disponibilidad
CREATE TABLE Disponibilidad (
    idDisponibilidad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        DATE NOT NULL,
    placa        VARCHAR2(20) NOT NULL,
    horaInicio   TIMESTAMP,
    horaFin      TIMESTAMP,
    tipoServicio VARCHAR2(30),
    CONSTRAINT fk_disponibilidad_vehiculo FOREIGN KEY (placa) REFERENCES Vehiculo(placa),
    CONSTRAINT ck_disponibilidad_horario CHECK (horaFin > horaInicio)
);

ALTER TABLE Disponibilidad
ADD Asignada NUMBER(1) DEFAULT 0 CHECK (Asignada IN (0, 1));

-- Crear la tabla Servicio
CREATE TABLE Servicio (
    idServicio      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR2(30),
    distancia       NUMBER(10,2),
    tarifa          NUMBER(10,2), 
    valorServicio   NUMBER(12,2) GENERATED ALWAYS AS (distancia * tarifa) VIRTUAL,
    horaInicio      TIMESTAMP,
    horaFin         TIMESTAMP,
    placa           VARCHAR2(20),
    clienteCedula VARCHAR2(20) NOT NULL,
    conductorCedula VARCHAR2(20),
    CONSTRAINT fk_servicioCliente FOREIGN KEY (clienteCedula) REFERENCES Usuario(cedula),
    CONSTRAINT fk_servicioConductor FOREIGN KEY (conductorCedula) REFERENCES Usuario(cedula),
    CONSTRAINT fk_vehiculo_placa FOREIGN KEY (placa) REFERENCES Vehiculo(placa)
);

ALTER TABLE Servicio 
MODIFY idServicio NUMBER GENERATED BY DEFAULT AS IDENTITY 
START WITH LIMIT VALUE;


-- Crear la tabla EntregaDomicilio
CREATE TABLE EntregaDomicilio (
    idServicio NUMBER PRIMARY KEY REFERENCES Servicio(idServicio),
    tarifaDomicilio NUMBER(12,2),
    ubicacionRestaurante VARCHAR2(200),
    puntoUsuario VARCHAR2(200)
);

-- Crear la tabla Rating
CREATE TABLE Rating (
    idComentario NUMBER PRIMARY KEY,
    idServicio NUMBER NOT NULL,
    revisor VARCHAR2(20) NOT NULL,
    revisado VARCHAR2(20) NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    comentario CLOB,
    fecha DATE,
    CONSTRAINT fk_idServicio FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio),
    CONSTRAINT fk_revisor FOREIGN KEY (revisor) REFERENCES Usuario(cedula),
    CONSTRAINT fk_revisado FOREIGN KEY (revisado) REFERENCES Usuario(cedula)
);

-- Crear la tabla TarjetaCredito
CREATE TABLE TarjetaCredito (
    numero NUMBER PRIMARY KEY,
    cedula VARCHAR2(20) NOT NULL,
    codigoSeguridad VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(120) NOT NULL,
    fechaVencimiento DATE NOT NULL,
    CONSTRAINT fk_tarjetacredito_usuario
        FOREIGN KEY (cedula)
        REFERENCES Usuario(cedula)
);

-- Crear la tabla TransporteMercancias
CREATE TABLE TransporteMercancias (
    idServicio NUMBER PRIMARY KEY REFERENCES Servicio(idServicio),
    tarifaMercancias NUMBER(12,2) NOT NULL
);

-- Crear la tabla TransportePasajeros
CREATE TABLE TransportePasajeros (
    idServicio NUMBER PRIMARY KEY REFERENCES Servicio(idServicio),
    tarifaPasajeros NUMBER(12,2) NOT NULL,
    nivelTransporte VARCHAR2(50) NOT NULL
);

-- Crear la tabla ServicioPunto (Para la realización del RFC4)
CREATE TABLE ServicioPunto (
    idServicioPunto NUMBER PRIMARY KEY,
    idServicio NUMBER NOT NULL,
    idPunto NUMBER NOT NULL,
    CONSTRAINT fk_sp_servicio FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio),
    CONSTRAINT fk_sp_punto FOREIGN KEY (idPunto) REFERENCES PuntoGeografico(idPunto)
);
